workflows:
  ios-workflow:
    name: iOS Workflow

    environment:
      xcode: latest
      node: 22

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Fix Capacitor permissions
        script: |
          chmod +x ./node_modules/.bin/capacitor

      - name: Sync Capacitor
        script: |
          ./node_modules/.bin/capacitor sync ios

    artifacts:
      - ios/App/build/**/*.ipa
      - /tmp/xcodebuild_logs/*.log